[SMTP]
from_addr=noreply@example.com
smtp_host=smtp.example.com
;<optional parameters>
smtp_port=587
username=user@example.com
password=***PASSWORD***
use_tls=True
use_ssl=False
timeout=10
[E-MAIL]
;<Alle Spaltennamen der Tabelle können als Platzhalter verwendet werden.>
subject=Aktuelle Adressliste
text_actual_data = Hallo {Vorname},
    aktuell sind folgende Daten von dir gespeichert:
    Name, Vorname: {Name}, {Vorname}
    E-Mail (privat): {E-Mail privat}
    E-Mail 2: {E-Mail 2}
    Telefon: {Telefon}
    Geburtsdatum: {Geburtsdatum}
    
    Wenn die Daten nicht mehr aktuell sind, bitte aktuelle Daten an mich senden.
    Falls du aus der Liste entfernt werden möchtest, ebenfalls melden.
    Viele Grüße

html_actual_data = <html>
                     <body>
                      <p>Hallo {Vorname},<br>
                         aktuell sind folgende Daten von dir gespeichert:<br>
                         Name, Vorname: {Name}, {Vorname}<br>
                         E-Mail (privat): {E-Mail privat}<br>
                         E-Mail 2: {E-Mail 2}<br>
                         Telefon: {Telefon}<br>
                         Geburtsdatum: {Geburtsdatum}</p>
                      <p>Wenn die Daten nicht mehr aktuell sind, bitte aktuelle Daten an mich senden.<br>
                         Falls du aus der Liste entfernt werden möchtest, ebenfalls melden.<br>
                         Viele Grüße</p>
                    </body>
                  </html>

text_actual_list = Hallo {Vorname},
     im Anhang ist die aktuelle Adressliste.
    Alternativ kann sie auch über den folgenden Link heruntergeladen werden:
    http://mycloud.net/adresslist
    
    Wenn deine Daten nicht mehr aktuell sind, bitte aktuelle Daten an mich senden.
    Falls du aus der Liste entfernt werden möchtest, ebenfalls melden.
    Viele Grüße

html_actual_list = <html>
                    <body>
                      <p>Hallo {Vorname},<br>
                         im Anhang ist die aktuelle Adressliste.<br>
                         Alternativ kann sie auch über den folgenden Link heruntergeladen werden:<br>
                         <a href="http://mycloud.net/adresslist">http://mycloud.net/adresslist</a></p>
                      <p>Wenn deine Daten nicht mehr aktuell sind, bitte aktuelle Daten an mich senden.<br>
                         Falls du aus der Liste entfernt werden möchtest, ebenfalls melden.<br>
                         Viele Grüße</p>
                    </body>
                  </html>

[TABLE]
headline_row=3
;<Diese Sektion ist optional.>
[EMAIL_LOGGING]
send_log_to=user@example.com
